services:
  - type: web
    name: n8n
    env: docker
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (defaults to master)
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-0-eu-west-1.pooler.supabase.com
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_PORT
        value: 6543
      - key: DB_POSTGRESDB_USER
        value: postgres.vtnqdcxaugstcxkmkpke
      - key: DB_POSTGRESDB_PASSWORD
        value: Cypla2705.mbg
      - key: DB_POSTGRESDB_SSL
        value: true
      - key: PORT
        value: 5678
      - key: N8N_LOG_LEVEL
        value: info
      - key: GENERIC_TIMEZONE
        value: Europe/Paris
      - key: TZ
        value: Europe/Paris
      - key: N8N_DEFAULT_LOCALE
        value: fr
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: EXECUTIONS_DATA_MAX_AGE
        value: 24
      - key: N8N_DIAGNOSTICS_ENABLED
        value: false
      - key: N8N_PERSONALIZATION_ENABLED
        value: false
      - key: N8N_METRICS
        value: false
      - key: DB_POSTGRESDB_POOL_SIZE
        value: 10
